"""Fixed executive grid zones — re-exported from layout engine (single source of truth)."""

from app.services.board_package.pptx_layout_engine import (  # noqa: F401
    CONTENT_W,
    FOOTNOTE_TOP,
    KPI_GAP,
    MARGIN_L,
    MARGIN_R,
    MAX_BULLETS,
    MAX_CALLOUTS,
    MAX_KPI_CARDS,
    MAX_TABLE_ROWS,
    SLIDE_HEIGHT,
    SLIDE_SAFE_BOTTOM,
    SLIDE_WIDTH_IN,
    ZONE_FOOTER_BOTTOM,
    ZONE_FOOTER_HEIGHT,
    ZONE_FOOTER_TOP,
    ZONE_KPI_BOTTOM,
    ZONE_KPI_HEIGHT,
    ZONE_KPI_TOP,
    ZONE_TITLE_BOTTOM,
    ZONE_VISUAL_BOTTOM,
    ZONE_VISUAL_HEIGHT,
    ZONE_VISUAL_TOP,
    ElementBox,
    footer_bullet_box,
    footer_zone,
    kpi_zone,
    takeaway_box,
    title_zone,
    visual_zone,
    visual_zone_chart,
    visual_zone_table,
)
