"""Generate header-only SMPL CSV templates (source inputs + calculated outputs)."""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def write_csv(rel_path: str, headers: list[str]) -> None:
    path = ROOT / rel_path
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(headers)


# --- ABS-012 Path A: customer source exports (ingest → canonical) ---
SOURCE_ABS012: dict[str, list[str]] = {
    "01-source-inputs/erp/ERP_GL_Detail_Export.csv": [
        "account_code",
        "account_name",
        "period",
        "amount",
        "debit_credit_indicator",
        "currency",
        "subsidiary",
        "journal_entry_id",
        "source_system",
    ],
    "01-source-inputs/erp/ERP_Chart_of_Accounts_Export.csv": [
        "account_code",
        "account_name",
        "account_type",
        "parent_account_code",
        "statement",
        "category",
    ],
    "01-source-inputs/erp/ERP_Trial_Balance_Export.csv": [
        "account_code",
        "account_name",
        "period",
        "debit_amount",
        "credit_amount",
        "ending_balance",
        "currency",
    ],
    "01-source-inputs/crm/CRM_Opportunity_Export.csv": [
        "opportunity_id",
        "opportunity_name",
        "account_name",
        "account_id",
        "stage",
        "amount",
        "close_date",
        "owner",
        "probability",
        "currency",
    ],
    "01-source-inputs/crm/CRM_Account_Export.csv": [
        "account_id",
        "account_name",
        "industry",
        "region",
        "segment",
        "owner",
        "source_crm",
    ],
    "01-source-inputs/crm/CRM_Pipeline_Export.csv": [
        "opportunity_id",
        "opportunity_name",
        "account_name",
        "stage",
        "amount",
        "expected_close_date",
        "owner",
        "forecast_category",
    ],
    "01-source-inputs/billing/Billing_Invoice_Register.csv": [
        "invoice_number",
        "customer_id",
        "customer_name",
        "invoice_date",
        "due_date",
        "amount",
        "subscription_plan",
        "payment_status",
        "currency",
        "service_period_start",
        "service_period_end",
        "billing_cadence",
    ],
    "01-source-inputs/billing/Billing_Subscription_Export.csv": [
        "subscription_id",
        "customer_id",
        "plan_name",
        "product",
        "start_date",
        "end_date",
        "mrr",
        "arr",
        "status",
        "currency",
        "billing_cadence",
    ],
    "01-source-inputs/billing/Billing_Customer_Export.csv": [
        "customer_id",
        "customer_name",
        "billing_email",
        "payment_terms",
        "currency",
        "status",
        "segment",
        "start_date",
    ],
    "01-source-inputs/hris/HRIS_Employee_Roster.csv": [
        "employee_id",
        "employee_name",
        "department",
        "title",
        "status",
        "start_date",
        "termination_date",
        "compensation_annual",
        "currency",
        "employment_type",
    ],
    "01-source-inputs/hris/HRIS_Headcount_Report.csv": [
        "employee_id",
        "employee_name",
        "department",
        "title",
        "status",
        "start_date",
        "termination_date",
    ],
    "01-source-inputs/hris/HRIS_Compensation_Export.csv": [
        "employee_id",
        "employee_name",
        "department",
        "title",
        "base_salary_annual",
        "variable_comp_annual",
        "benefits_load_pct",
        "currency",
    ],
}

# --- Operational typed marts (loader EXPECTED / EXPANDED profiles) ---
OPERATIONAL_MARTS: dict[str, list[str]] = {
    "02-operational-marts/customers.csv": [
        "customer_id",
        "customer_name",
        "segment",
        "industry",
        "status",
        "customer_start_date",
        "contract_start_date",
        "billing_cadence",
        "billing_terms",
        "billing_state",
        "source_crm",
        "netsuite_customer_id",
        "stripe_customer_id",
        "starting_mrr_jan_2026",
        "starting_arr_jan_2026",
        "currency",
    ],
    "02-operational-marts/subscriptions.csv": [
        "subscription_id",
        "customer_id",
        "product",
        "billing_cadence",
        "contract_start_date",
        "contract_end_date",
        "current_mrr",
        "current_arr",
        "status",
        "source_opportunity_id",
        "currency",
        "version",
    ],
    "02-operational-marts/opportunities.csv": [
        "opportunity_id",
        "customer_id",
        "customer_name",
        "opportunity_name",
        "opportunity_type",
        "stage",
        "amount_arr",
        "expected_close_date",
        "close_date",
        "contract_start_date",
        "probability",
        "segment",
        "owner_rep_id",
        "owner",
        "forecast_period",
        "source_crm",
        "marketing_channel",
        "version",
    ],
    "02-operational-marts/invoices.csv": [
        "version",
        "invoice_id",
        "customer_id",
        "customer_name",
        "invoice_period",
        "service_period_start",
        "service_period_end",
        "invoice_date",
        "due_date",
        "invoice_amount",
        "payment_status",
        "billing_cadence",
        "billing_terms",
        "currency",
    ],
    "02-operational-marts/payments.csv": [
        "version",
        "payment_id",
        "invoice_id",
        "customer_id",
        "payment_date",
        "payment_amount",
        "payment_method",
        "currency",
    ],
    "02-operational-marts/gl_actuals.csv": [
        "version",
        "period",
        "account_number",
        "account_name",
        "statement",
        "statement_category",
        "account_group",
        "expense_type",
        "department",
        "cost_center",
        "sub_department",
        "vendor_id",
        "vendor_name",
        "source_file",
        "source_record_id",
        "amount",
        "currency",
        "subsidiary",
        "source_system",
        "notes",
    ],
    "02-operational-marts/headcount_plan.csv": [
        "version",
        "period",
        "department",
        "headcount",
        "monthly_payroll_cost",
        "payroll_tax_rate",
        "benefits_rate",
        "total_people_cost",
    ],
    "02-operational-marts/vendor_contracts.csv": [
        "vendor_id",
        "vendor_name",
        "service_category",
        "contract_start",
        "contract_end",
        "annual_contract_value",
        "billing_cadence",
        "payment_terms",
        "expense_category",
    ],
    "02-operational-marts/sales_quotas.csv": [
        "rep_id",
        "rep_name",
        "role",
        "segment",
        "quota_period",
        "quota_arr",
        "closed_won_arr_to_date",
    ],
    "02-operational-marts/commission_plans.csv": [
        "plan_id",
        "role",
        "eligible_opportunity_type",
        "base_commission_rate",
        "accelerator_multiplier",
        "accelerator_threshold",
        "accelerated_rate",
        "clawback_window_months",
    ],
    "02-operational-marts/mrr_waterfall_customer_level.csv": [
        "period",
        "customer_id",
        "beginning_mrr",
        "new_mrr",
        "expansion_mrr",
        "contraction_mrr",
        "churn_mrr",
        "reactivation_mrr",
        "ending_mrr",
        "movement_type",
    ],
    "02-operational-marts/forecast_assumptions.csv": [
        "assumption",
        "value",
    ],
    "02-operational-marts/forecast_gl_detail.csv": [
        "scenario",
        "period",
        "line_type",
        "statement_category",
        "department",
        "sub_department",
        "account_group",
        "expense_type",
        "gl_account",
        "management_view_include",
        "accounting_view_include",
        "sbc_flag",
        "one_time_flag",
        "non_cash_flag",
        "forecast_amount",
        "source",
        "notes",
    ],
    "02-operational-marts/forecast_bookings_summary.csv": [
        "version",
        "period",
        "gross_bookings_arr",
        "weighted_pipeline_arr",
        "pipeline_coverage_ratio",
        "new_business_arr",
        "renewal_arr",
        "expansion_arr",
    ],
    "02-operational-marts/forecast_cash_collections.csv": [
        "version",
        "period",
        "beginning_cash",
        "collections",
        "payroll_cash_out",
        "commission_cash_out",
        "vendor_cash_out",
        "marketing_cash_out",
        "ending_cash",
    ],
    "02-operational-marts/forecast_cash_flow_statement.csv": [
        "version",
        "period",
        "net_income",
        "change_in_accounts_receivable",
        "change_in_deferred_revenue",
        "capital_expenditures",
        "net_cash_from_operating_activities",
        "ending_cash",
    ],
    "02-operational-marts/forecast_balance_sheet.csv": [
        "version",
        "period",
        "cash",
        "accounts_receivable",
        "deferred_revenue",
        "accounts_payable",
        "total_assets",
        "total_liabilities",
        "equity",
    ],
    "02-operational-marts/forecast_income_statement.csv": [
        "version",
        "period",
        "revenue",
        "cost_of_revenue",
        "gross_profit",
        "sales_and_marketing",
        "research_and_development",
        "general_and_administrative",
        "ebitda",
        "net_income",
    ],
    "02-operational-marts/forecast_headcount_plan.csv": [
        "version",
        "period",
        "department",
        "headcount",
        "monthly_payroll_cost",
        "total_people_cost",
    ],
    "02-operational-marts/forecast_marketing_pipeline.csv": [
        "version",
        "period",
        "marketing_channel",
        "mqls",
        "sqls",
        "pipeline_arr_created",
        "expected_closed_won_arr",
        "marketing_spend",
        "cost_per_sql",
    ],
    "02-operational-marts/forecast_mrr_waterfall.csv": [
        "version",
        "period",
        "beginning_arr",
        "renewal_arr",
        "new_business_arr",
        "expansion_arr",
        "contraction_arr",
        "churn_arr",
        "reactivation_arr",
        "net_new_arr",
        "ending_arr",
        "gross_retention_rate",
        "net_dollar_retention_rate",
        "waterfall_check",
    ],
    "02-operational-marts/forecast_opportunities.csv": [
        "version",
        "forecast_period",
        "opportunity_id",
        "customer_id",
        "customer_name",
        "segment",
        "region",
        "marketing_channel",
        "opportunity_type",
        "stage",
        "amount_arr",
        "probability",
        "weighted_arr",
        "billing_cadence",
        "billing_terms",
        "historical_nrr_assumption",
    ],
    "02-operational-marts/forecast_quota_capacity.csv": [
        "version",
        "period",
        "region",
        "quota_carrying_reps",
        "quota_capacity_arr",
        "expected_bookings_arr",
    ],
    "02-operational-marts/forecast_revenue_schedule.csv": [
        "version",
        "period",
        "recognized_revenue",
        "billings",
        "deferred_revenue_ending",
        "historical_dso",
        "expected_collections",
    ],
    "02-operational-marts/forecast_working_capital_metrics.csv": [
        "version",
        "period",
        "dso",
        "dpo",
        "accounts_receivable",
        "deferred_revenue",
    ],
}

WORKFORCE_MARTS: dict[str, list[str]] = {
    "02-operational-marts/workforce/workforce_employees.csv": [
        "employee_id",
        "employee_name",
        "scenario",
        "department",
        "sub_department",
        "role",
        "level",
        "region",
        "manager",
        "employment_status",
        "hire_date",
        "termination_date",
        "base_salary",
        "variable_comp",
        "commission_target",
        "equity_sbc_annual",
        "benefits_load_pct",
        "fully_loaded_cash_cost",
        "fully_loaded_gaap_cost",
        "quota_carrying",
        "annual_quota_arr",
        "productivity_ramp_months",
        "remote_flag",
        "source",
    ],
    "02-operational-marts/workforce/workforce_open_requisitions.csv": [
        "req_id",
        "role",
        "department",
        "planned_start_date",
        "approved_status",
        "requisition_type",
    ],
    "02-operational-marts/workforce/workforce_hiring_ramp_assumptions.csv": [
        "ramp_months",
        "month_after_start",
        "productivity_pct",
        "applies_to",
    ],
    "02-operational-marts/workforce/workforce_compensation_bands.csv": [
        "department",
        "role",
        "level",
        "salary_midpoint",
        "salary_low",
        "salary_high",
        "variable_comp_target",
        "equity_sbc_annual",
        "benefits_load_pct",
        "fully_loaded_cash_cost_midpoint",
        "fully_loaded_gaap_cost_midpoint",
        "quota_carrying",
        "annual_quota_arr",
        "productivity_ramp_months",
    ],
    "02-operational-marts/workforce/workforce_department_allocation_rules.csv": [
        "department",
        "statement_category",
        "sub_department_mapping",
        "allocation_description",
        "allocation_pct",
    ],
}

# --- Reporting / calculated outputs (SMPL upload filenames → physical warehouse tables) ---
REPORTING_SCHEMAS: dict[str, list[str]] = {
    "mrr_waterfall": [
        "period",
        "beginning_arr",
        "renewal_arr",
        "new_business_arr",
        "expansion_arr",
        "contraction_arr",
        "churn_arr",
        "reactivation_arr",
        "net_new_arr",
        "ending_arr",
        "gross_retention_rate",
        "net_dollar_retention_rate",
        "waterfall_check",
    ],
    "income_statement": [
        "period",
        "revenue",
        "cost_of_revenue",
        "gross_profit",
        "gross_margin_percent",
        "sales_and_marketing",
        "research_and_development",
        "general_and_administrative",
        "total_opex",
        "ebitda",
        "depreciation_amortization",
        "operating_income",
        "net_income",
    ],
    "balance_sheet": [
        "period",
        "cash",
        "accounts_receivable",
        "deferred_revenue",
        "accounts_payable",
        "prepaid_expenses",
        "other_current_assets",
        "total_assets",
        "total_liabilities",
        "equity",
        "retained_earnings",
    ],
    "cash_flow_bridge": [
        "period",
        "beginning_cash",
        "collections",
        "payroll_cash_out",
        "commission_cash_out",
        "vendor_cash_out_n30",
        "tax_cash_out",
        "interest_cash_out",
        "other_operating_cash_out",
        "capex",
        "financing_to_maintain_cash_floor",
        "ending_cash",
        "cash_floor",
    ],
    "cash_flow_statement": [
        "period",
        "net_income",
        "depreciation_amortization",
        "stock_based_compensation",
        "change_in_accounts_receivable",
        "change_in_deferred_revenue",
        "change_in_accounts_payable",
        "change_in_prepaids",
        "change_in_other_working_capital",
        "capital_expenditures",
        "net_cash_from_operating_activities",
        "net_cash_from_investing_activities",
        "net_cash_from_financing_activities",
        "ending_cash",
    ],
    "marketing_pipeline": [
        "period",
        "marketing_channel",
        "marketing_spend",
        "mqls",
        "sqls",
        "sals",
        "opportunities_created",
        "pipeline_arr_created",
        "closed_won_arr",
        "closed_lost_arr",
        "cost_per_mql",
    ],
    "marketing_spend_by_channel": [
        "period",
        "marketing_channel",
        "marketing_spend",
        "mqls",
        "sqls",
        "pipeline_arr_created",
        "closed_won_arr",
    ],
    "pipeline_waterfall": [
        "period",
        "beginning_pipeline",
        "pipeline_created",
        "closed_won",
        "closed_lost",
        "slipped_pipeline",
        "ending_pipeline",
        "weighted_pipeline",
        "pipeline_coverage_ratio",
    ],
    "opportunity_movements": [
        "period",
        "opportunity_id",
        "opportunity_name",
        "customer_id",
        "customer_name",
        "opportunity_type",
        "stage",
        "close_status",
        "created_date",
        "expected_close_date",
        "actual_close_date",
        "contract_start_date",
        "contract_end_date",
        "contract_term_months",
        "billing_cadence",
        "billing_terms",
        "customer_state",
        "region",
        "segment",
        "industry",
        "marketing_channel",
        "owner",
        "amount_arr",
        "weighted_arr",
        "probability",
        "waterfall_type",
        "pipeline_movement_type",
        "arr_impact",
        "source_note",
    ],
    "deferred_revenue_waterfall": [
        "period",
        "beginning_deferred",
        "billings",
        "revenue_recognized",
        "ending_deferred",
    ],
    "headcount_plan": [
        "period",
        "department",
        "headcount_beginning",
        "new_hires",
        "attrition",
        "headcount_ending",
        "monthly_payroll_cost",
        "payroll_tax_rate",
        "benefits_rate",
        "total_people_cost",
        "quota_capacity",
    ],
    "sales_quotas": [
        "rep_id",
        "rep_name",
        "role",
        "segment",
        "quota_period",
        "quota_arr",
        "closed_won_arr_to_date",
        "attainment_pct",
    ],
    "opportunities": [
        "period",
        "opportunity_id",
        "customer_id",
        "customer_name",
        "opportunity_name",
        "opportunity_type",
        "stage",
        "amount_arr",
        "probability",
        "weighted_arr",
        "marketing_channel",
        "region",
        "segment",
        "owner",
        "expected_close_date",
    ],
    "employees": [
        "employee_id",
        "employee_name",
        "department",
        "role",
        "level",
        "employment_status",
        "hire_date",
        "termination_date",
        "base_salary",
        "fully_loaded_cash_cost",
        "quota_carrying",
        "annual_quota_arr",
    ],
    "gl_detail": [
        "period",
        "line_type",
        "statement_category",
        "department",
        "sub_department",
        "account_group",
        "expense_type",
        "gl_account",
        "management_view_include",
        "accounting_view_include",
        "sbc_flag",
        "one_time_flag",
        "non_cash_flag",
        "amount",
        "source",
        "notes",
    ],
    "bookings_summary": [
        "period",
        "gross_bookings_arr",
        "weighted_pipeline_arr",
        "pipeline_coverage_ratio",
        "new_business_arr",
        "renewal_arr",
        "expansion_arr",
    ],
    "revenue_schedule": [
        "period",
        "recognized_revenue",
        "billings",
        "deferred_revenue_ending",
        "historical_dso",
        "expected_collections",
    ],
    "working_capital_metrics": [
        "period",
        "dso",
        "dpo",
        "accounts_receivable",
        "deferred_revenue",
    ],
}

VERSION_PREFIXES = ("Actual", "Forecast", "Budget")


def _pascal_dataset(stem: str) -> str:
  """Map schema key to SMPL filename stem (PascalCase segments)."""
  special = {
      "mrr_waterfall": "MRR_Waterfall",
      "gl_detail": "gl_detail",
      "headcount_plan": "Headcount_Plan",
      "sales_quotas": "Sales_Quotas",
      "marketing_spend_by_channel": "marketing_spend_by_channel",
  }
  if stem in special:
      return special[stem]
  return "".join(part.capitalize() for part in stem.split("_"))


def generate_reporting_outputs() -> None:
    for prefix in VERSION_PREFIXES:
        folder = f"03-calculated-outputs/{prefix.lower()}"
        for stem, headers in REPORTING_SCHEMAS.items():
            dataset = _pascal_dataset(stem)
            write_csv(f"{folder}/{prefix}_{dataset}.csv", headers)


def main() -> None:
    for rel, headers in SOURCE_ABS012.items():
        write_csv(rel, headers)
    for rel, headers in OPERATIONAL_MARTS.items():
        write_csv(rel, headers)
    for rel, headers in WORKFORCE_MARTS.items():
        write_csv(rel, headers)
    generate_reporting_outputs()
    count = sum(1 for _ in ROOT.rglob("*.csv"))
    print(f"Wrote {count} header-only CSV templates under:")
    print(f"  {ROOT}")
    print("  (one header row per file — no data rows; run calculation_lineage.py for trace-back export)")


if __name__ == "__main__":
    main()
