"""add financial domain tables

Revision ID: e468aa4669fc
Revises: 20250512_0001
Create Date: 2026-05-12 13:30:01.956375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e468aa4669fc'
down_revision: Union[str, None] = '20250512_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_reporting_commentary',
    sa.Column('report_kind', sa.Enum('executive_summary', 'mrr_waterfall', 'bookings', 'revenue', 'cash', 'board_pack', 'other', name='aicommentaryreportkind', native_enum=False), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('source_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Pointers to forecast scenario ids, KPI snapshots, etc.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_commentary_org_kind_period', 'ai_reporting_commentary', ['organization_id', 'report_kind', 'period_start'], unique=False)
    op.create_index(op.f('ix_ai_reporting_commentary_organization_id'), 'ai_reporting_commentary', ['organization_id'], unique=False)
    op.create_table('commission_plans',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('effective_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', 'effective_start', name='uq_commission_plans_org_name_start')
    )
    op.create_index('ix_commission_plans_org_effective', 'commission_plans', ['organization_id', 'effective_start'], unique=False)
    op.create_index(op.f('ix_commission_plans_organization_id'), 'commission_plans', ['organization_id'], unique=False)
    op.create_table('customers',
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('external_crm_account_id', sa.String(length=128), nullable=True),
    sa.Column('external_billing_customer_id', sa.String(length=128), nullable=True),
    sa.Column('external_erp_entity_id', sa.String(length=128), nullable=True),
    sa.Column('source_system', sa.Enum('salesforce', 'hubspot', 'netsuite', 'stripe', 'csv', 'manual', 'other', name='sourcesystem', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('billing_country', sa.String(length=2), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'source_system', 'external_id', name='uq_customers_org_source_external')
    )
    op.create_index('ix_customers_org_billing', 'customers', ['organization_id', 'external_billing_customer_id'], unique=False)
    op.create_index('ix_customers_org_crm', 'customers', ['organization_id', 'external_crm_account_id'], unique=False)
    op.create_index('ix_customers_org_erp', 'customers', ['organization_id', 'external_erp_entity_id'], unique=False)
    op.create_index('ix_customers_org_name', 'customers', ['organization_id', 'name'], unique=False)
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_table('forecast_scenarios',
    sa.Column('scenario_kind', sa.Enum('bookings', 'revenue', 'cash', name='forecastscenariokind', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('as_of_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'scenario_kind', 'name', 'as_of_date', name='uq_forecast_scenarios_org_kind_name_asof')
    )
    op.create_index('ix_forecast_scenarios_org_kind', 'forecast_scenarios', ['organization_id', 'scenario_kind'], unique=False)
    op.create_index(op.f('ix_forecast_scenarios_organization_id'), 'forecast_scenarios', ['organization_id'], unique=False)
    op.create_table('gl_accounts',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('account_type', sa.Enum('asset', 'liability', 'equity', 'revenue', 'cogs', 'opex', 'other_income_expense', name='glaccounttype', native_enum=False), nullable=False),
    sa.Column('statement_line', sa.Enum('income_statement', 'balance_sheet', 'cash_flow', 'memo', name='glstatementline', native_enum=False), nullable=False),
    sa.Column('parent_account_id', sa.UUID(), nullable=True),
    sa.Column('source_system', sa.Enum('salesforce', 'hubspot', 'netsuite', 'stripe', 'csv', 'manual', 'other', name='sourcesystem', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_account_id'], ['gl_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'source_system', 'external_id', name='uq_gl_accounts_org_source_external')
    )
    op.create_index('ix_gl_accounts_org_type', 'gl_accounts', ['organization_id', 'account_type'], unique=False)
    op.create_index(op.f('ix_gl_accounts_organization_id'), 'gl_accounts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_gl_accounts_parent_account_id'), 'gl_accounts', ['parent_account_id'], unique=False)
    op.create_table('sales_reps',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_system', sa.Enum('salesforce', 'hubspot', 'netsuite', 'stripe', 'csv', 'manual', 'other', name='sourcesystem', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'source_system', 'external_id', name='uq_sales_reps_org_source_external')
    )
    op.create_index('ix_sales_reps_org_email', 'sales_reps', ['organization_id', 'email'], unique=False)
    op.create_index(op.f('ix_sales_reps_organization_id'), 'sales_reps', ['organization_id'], unique=False)
    op.create_table('clawback_rules',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.Enum('invoice_default', 'churn_within_window', 'deal_reversal', 'manual', name='clawbacktrigger', native_enum=False), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=True),
    sa.Column('clawback_percent', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('extra_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('clawback_percent >= 0 AND clawback_percent <= 1', name='ck_clawback_pct_0_1'),
    sa.CheckConstraint('lookback_days IS NULL OR lookback_days >= 0', name='ck_clawback_lookback_non_negative'),
    sa.ForeignKeyConstraint(['plan_id'], ['commission_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clawback_rules_plan_id'), 'clawback_rules', ['plan_id'], unique=False)
    op.create_table('commission_payouts',
    sa.Column('sales_rep_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('calculated', 'approved', 'paid', 'void', name='commissionpayoutstatus', native_enum=False), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['commission_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_reps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'sales_rep_id', 'plan_id', 'period_start', name='uq_commission_payouts_org_rep_plan_period')
    )
    op.create_index('ix_commission_payouts_org_status', 'commission_payouts', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_commission_payouts_organization_id'), 'commission_payouts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commission_payouts_plan_id'), 'commission_payouts', ['plan_id'], unique=False)
    op.create_index(op.f('ix_commission_payouts_sales_rep_id'), 'commission_payouts', ['sales_rep_id'], unique=False)
    op.create_table('commission_plan_rules',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('rule_kind', sa.Enum('flat_rate_on_bookings', 'tiered_on_quota_attainment', 'split_across_reps', 'accelerator', 'draw_against_commission', 'other', name='commissionplanrulekind', native_enum=False), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['commission_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commission_plan_rules_plan', 'commission_plan_rules', ['plan_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_commission_plan_rules_plan_id'), 'commission_plan_rules', ['plan_id'], unique=False)
    op.create_table('crm_opportunities',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('owner_rep_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('stage', sa.Enum('prospecting', 'qualified', 'proposal', 'negotiation', 'closed_won', 'closed_lost', name='opportunitystage', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('probability', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('expected_close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.Enum('salesforce', 'hubspot', 'netsuite', 'stripe', 'csv', 'manual', 'other', name='sourcesystem', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False, comment='True when the deal counts toward bookings / attainment per your policy'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_opportunities_amount_non_negative'),
    sa.CheckConstraint('probability IS NULL OR (probability >= 0 AND probability <= 1)', name='ck_opportunities_probability_0_1'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_rep_id'], ['sales_reps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'source_system', 'external_id', name='uq_opportunities_org_source_external')
    )
    op.create_index(op.f('ix_crm_opportunities_customer_id'), 'crm_opportunities', ['customer_id'], unique=False)
    op.create_index(op.f('ix_crm_opportunities_organization_id'), 'crm_opportunities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_crm_opportunities_owner_rep_id'), 'crm_opportunities', ['owner_rep_id'], unique=False)
    op.create_index('ix_opportunities_org_close_date', 'crm_opportunities', ['organization_id', 'expected_close_date'], unique=False)
    op.create_index('ix_opportunities_org_customer', 'crm_opportunities', ['organization_id', 'customer_id'], unique=False)
    op.create_index('ix_opportunities_org_stage', 'crm_opportunities', ['organization_id', 'stage'], unique=False)
    op.create_table('gl_actuals',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subsidiary_code', sa.String(length=64), nullable=False, comment='Empty string = consolidated / default subsidiary'),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_system', sa.Enum('salesforce', 'hubspot', 'netsuite', 'stripe', 'csv', 'manual', 'other', name='sourcesystem', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('debit >= 0 AND credit >= 0', name='ck_gl_actuals_debit_credit_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['gl_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'account_id', 'period_start', 'subsidiary_code', name='uq_gl_actuals_org_account_period_sub')
    )
    op.create_index(op.f('ix_gl_actuals_account_id'), 'gl_actuals', ['account_id'], unique=False)
    op.create_index('ix_gl_actuals_org_period', 'gl_actuals', ['organization_id', 'period_start'], unique=False)
    op.create_index(op.f('ix_gl_actuals_organization_id'), 'gl_actuals', ['organization_id'], unique=False)
    op.create_table('payments',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('source_system', sa.Enum('salesforce', 'hubspot', 'netsuite', 'stripe', 'csv', 'manual', 'other', name='sourcesystem', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'source_system', 'external_id', name='uq_payments_org_source_external')
    )
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index('ix_payments_org_customer', 'payments', ['organization_id', 'customer_id'], unique=False)
    op.create_index('ix_payments_org_effective', 'payments', ['organization_id', 'effective_date'], unique=False)
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_table('quotas',
    sa.Column('sales_rep_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quota_kind', sa.String(length=64), nullable=False, comment='e.g. bookings_arr, new_logo_acv, expansion_arr'),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_reps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'sales_rep_id', 'period_start', 'quota_kind', name='uq_quotas_org_rep_period_kind')
    )
    op.create_index('ix_quotas_org_period', 'quotas', ['organization_id', 'period_start'], unique=False)
    op.create_index(op.f('ix_quotas_organization_id'), 'quotas', ['organization_id'], unique=False)
    op.create_index(op.f('ix_quotas_sales_rep_id'), 'quotas', ['sales_rep_id'], unique=False)
    op.create_table('bookings_forecast_lines',
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('forecast_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('probability_weight', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('forecast_amount >= 0', name='ck_bookings_fc_amount_non_negative'),
    sa.CheckConstraint('probability_weight IS NULL OR (probability_weight >= 0 AND probability_weight <= 1)', name='ck_bookings_fc_probability_0_1'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['crm_opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['forecast_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_fc_scenario_period', 'bookings_forecast_lines', ['scenario_id', 'period_start'], unique=False)
    op.create_index(op.f('ix_bookings_forecast_lines_customer_id'), 'bookings_forecast_lines', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_forecast_lines_opportunity_id'), 'bookings_forecast_lines', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_bookings_forecast_lines_scenario_id'), 'bookings_forecast_lines', ['scenario_id'], unique=False)
    op.create_table('commission_payout_lines',
    sa.Column('payout_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('basis_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quota_attainment_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Optional frozen JSON: quota targets vs closed-won for the period'),
    sa.Column('calculation_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['crm_opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payout_id'], ['commission_payouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commission_payout_lines_opportunity', 'commission_payout_lines', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_commission_payout_lines_opportunity_id'), 'commission_payout_lines', ['opportunity_id'], unique=False)
    op.create_index('ix_commission_payout_lines_payout', 'commission_payout_lines', ['payout_id'], unique=False)
    op.create_index(op.f('ix_commission_payout_lines_payout_id'), 'commission_payout_lines', ['payout_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('originating_opportunity_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'trialing', 'past_due', 'canceled', 'paused', name='subscriptionstatus', native_enum=False), nullable=False),
    sa.Column('mrr_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='Normalized monthly recurring revenue in invoice currency'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.Enum('salesforce', 'hubspot', 'netsuite', 'stripe', 'csv', 'manual', 'other', name='sourcesystem', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('mrr_amount >= 0', name='ck_subscriptions_mrr_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['originating_opportunity_id'], ['crm_opportunities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'source_system', 'external_id', name='uq_subscriptions_org_source_external')
    )
    op.create_index(op.f('ix_subscriptions_customer_id'), 'subscriptions', ['customer_id'], unique=False)
    op.create_index('ix_subscriptions_org_customer', 'subscriptions', ['organization_id', 'customer_id'], unique=False)
    op.create_index('ix_subscriptions_org_status', 'subscriptions', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_originating_opportunity_id'), 'subscriptions', ['originating_opportunity_id'], unique=False)
    op.create_table('invoices',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'open', 'paid', 'void', 'uncollectible', name='invoicestatus', native_enum=False), nullable=False),
    sa.Column('issued_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_system', sa.Enum('salesforce', 'hubspot', 'netsuite', 'stripe', 'csv', 'manual', 'other', name='sourcesystem', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('payment_terms_days >= 0', name='ck_invoices_terms_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_invoices_total_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'source_system', 'external_id', name='uq_invoices_org_source_external')
    )
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index('ix_invoices_org_customer', 'invoices', ['organization_id', 'customer_id'], unique=False)
    op.create_index('ix_invoices_org_due', 'invoices', ['organization_id', 'due_date'], unique=False)
    op.create_index('ix_invoices_org_status', 'invoices', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    op.create_table('mrr_movements',
    sa.Column('movement_month', sa.DateTime(timezone=True), nullable=False, comment='Anchor as first instant of calendar month (UTC or tenant TZ in app layer)'),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('movement_kind', sa.Enum('new', 'expansion', 'contraction', 'churn', 'reactivation', name='mrrmovementkind', native_enum=False), nullable=False),
    sa.Column('mrr_delta', sa.Numeric(precision=18, scale=2), nullable=False, comment='Change in MRR vs prior month for this bucket'),
    sa.Column('prior_mrr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_mrr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mrr_movements_customer_id'), 'mrr_movements', ['customer_id'], unique=False)
    op.create_index('ix_mrr_movements_org_customer', 'mrr_movements', ['organization_id', 'customer_id'], unique=False)
    op.create_index('ix_mrr_movements_org_kind', 'mrr_movements', ['organization_id', 'movement_kind'], unique=False)
    op.create_index('ix_mrr_movements_org_period', 'mrr_movements', ['organization_id', 'movement_month'], unique=False)
    op.create_index(op.f('ix_mrr_movements_organization_id'), 'mrr_movements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_mrr_movements_subscription_id'), 'mrr_movements', ['subscription_id'], unique=False)
    op.create_table('revenue_forecast_lines',
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('recognized_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('deferred_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('recognized_amount >= 0', name='ck_revenue_fc_recognized_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['forecast_scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_revenue_fc_scenario_period', 'revenue_forecast_lines', ['scenario_id', 'period_start'], unique=False)
    op.create_index(op.f('ix_revenue_forecast_lines_customer_id'), 'revenue_forecast_lines', ['customer_id'], unique=False)
    op.create_index(op.f('ix_revenue_forecast_lines_scenario_id'), 'revenue_forecast_lines', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_revenue_forecast_lines_subscription_id'), 'revenue_forecast_lines', ['subscription_id'], unique=False)
    op.create_table('cash_forecast_lines',
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('expected_collections', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expected_collections >= 0', name='ck_cash_fc_collections_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['forecast_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cash_fc_scenario_period', 'cash_forecast_lines', ['scenario_id', 'period_start'], unique=False)
    op.create_index(op.f('ix_cash_forecast_lines_customer_id'), 'cash_forecast_lines', ['customer_id'], unique=False)
    op.create_index(op.f('ix_cash_forecast_lines_invoice_id'), 'cash_forecast_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_cash_forecast_lines_scenario_id'), 'cash_forecast_lines', ['scenario_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_invoice_line_qty_positive'),
    sa.CheckConstraint('unit_amount >= 0', name='ck_invoice_line_unit_non_negative'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_line_items_invoice', 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allocated_amount > 0', name='ck_payment_alloc_amount_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_alloc_invoice', 'payment_allocations', ['invoice_id'], unique=False)
    op.create_index('ix_payment_alloc_payment', 'payment_allocations', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_alloc_payment', table_name='payment_allocations')
    op.drop_index('ix_payment_alloc_invoice', table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index('ix_invoice_line_items_invoice', table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_cash_forecast_lines_scenario_id'), table_name='cash_forecast_lines')
    op.drop_index(op.f('ix_cash_forecast_lines_invoice_id'), table_name='cash_forecast_lines')
    op.drop_index(op.f('ix_cash_forecast_lines_customer_id'), table_name='cash_forecast_lines')
    op.drop_index('ix_cash_fc_scenario_period', table_name='cash_forecast_lines')
    op.drop_table('cash_forecast_lines')
    op.drop_index(op.f('ix_revenue_forecast_lines_subscription_id'), table_name='revenue_forecast_lines')
    op.drop_index(op.f('ix_revenue_forecast_lines_scenario_id'), table_name='revenue_forecast_lines')
    op.drop_index(op.f('ix_revenue_forecast_lines_customer_id'), table_name='revenue_forecast_lines')
    op.drop_index('ix_revenue_fc_scenario_period', table_name='revenue_forecast_lines')
    op.drop_table('revenue_forecast_lines')
    op.drop_index(op.f('ix_mrr_movements_subscription_id'), table_name='mrr_movements')
    op.drop_index(op.f('ix_mrr_movements_organization_id'), table_name='mrr_movements')
    op.drop_index('ix_mrr_movements_org_period', table_name='mrr_movements')
    op.drop_index('ix_mrr_movements_org_kind', table_name='mrr_movements')
    op.drop_index('ix_mrr_movements_org_customer', table_name='mrr_movements')
    op.drop_index(op.f('ix_mrr_movements_customer_id'), table_name='mrr_movements')
    op.drop_table('mrr_movements')
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.drop_index('ix_invoices_org_status', table_name='invoices')
    op.drop_index('ix_invoices_org_due', table_name='invoices')
    op.drop_index('ix_invoices_org_customer', table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_subscriptions_originating_opportunity_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_org_status', table_name='subscriptions')
    op.drop_index('ix_subscriptions_org_customer', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_commission_payout_lines_payout_id'), table_name='commission_payout_lines')
    op.drop_index('ix_commission_payout_lines_payout', table_name='commission_payout_lines')
    op.drop_index(op.f('ix_commission_payout_lines_opportunity_id'), table_name='commission_payout_lines')
    op.drop_index('ix_commission_payout_lines_opportunity', table_name='commission_payout_lines')
    op.drop_table('commission_payout_lines')
    op.drop_index(op.f('ix_bookings_forecast_lines_scenario_id'), table_name='bookings_forecast_lines')
    op.drop_index(op.f('ix_bookings_forecast_lines_opportunity_id'), table_name='bookings_forecast_lines')
    op.drop_index(op.f('ix_bookings_forecast_lines_customer_id'), table_name='bookings_forecast_lines')
    op.drop_index('ix_bookings_fc_scenario_period', table_name='bookings_forecast_lines')
    op.drop_table('bookings_forecast_lines')
    op.drop_index(op.f('ix_quotas_sales_rep_id'), table_name='quotas')
    op.drop_index(op.f('ix_quotas_organization_id'), table_name='quotas')
    op.drop_index('ix_quotas_org_period', table_name='quotas')
    op.drop_table('quotas')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_index('ix_payments_org_effective', table_name='payments')
    op.drop_index('ix_payments_org_customer', table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_gl_actuals_organization_id'), table_name='gl_actuals')
    op.drop_index('ix_gl_actuals_org_period', table_name='gl_actuals')
    op.drop_index(op.f('ix_gl_actuals_account_id'), table_name='gl_actuals')
    op.drop_table('gl_actuals')
    op.drop_index('ix_opportunities_org_stage', table_name='crm_opportunities')
    op.drop_index('ix_opportunities_org_customer', table_name='crm_opportunities')
    op.drop_index('ix_opportunities_org_close_date', table_name='crm_opportunities')
    op.drop_index(op.f('ix_crm_opportunities_owner_rep_id'), table_name='crm_opportunities')
    op.drop_index(op.f('ix_crm_opportunities_organization_id'), table_name='crm_opportunities')
    op.drop_index(op.f('ix_crm_opportunities_customer_id'), table_name='crm_opportunities')
    op.drop_table('crm_opportunities')
    op.drop_index(op.f('ix_commission_plan_rules_plan_id'), table_name='commission_plan_rules')
    op.drop_index('ix_commission_plan_rules_plan', table_name='commission_plan_rules')
    op.drop_table('commission_plan_rules')
    op.drop_index(op.f('ix_commission_payouts_sales_rep_id'), table_name='commission_payouts')
    op.drop_index(op.f('ix_commission_payouts_plan_id'), table_name='commission_payouts')
    op.drop_index(op.f('ix_commission_payouts_organization_id'), table_name='commission_payouts')
    op.drop_index('ix_commission_payouts_org_status', table_name='commission_payouts')
    op.drop_table('commission_payouts')
    op.drop_index(op.f('ix_clawback_rules_plan_id'), table_name='clawback_rules')
    op.drop_table('clawback_rules')
    op.drop_index(op.f('ix_sales_reps_organization_id'), table_name='sales_reps')
    op.drop_index('ix_sales_reps_org_email', table_name='sales_reps')
    op.drop_table('sales_reps')
    op.drop_index(op.f('ix_gl_accounts_parent_account_id'), table_name='gl_accounts')
    op.drop_index(op.f('ix_gl_accounts_organization_id'), table_name='gl_accounts')
    op.drop_index('ix_gl_accounts_org_type', table_name='gl_accounts')
    op.drop_table('gl_accounts')
    op.drop_index(op.f('ix_forecast_scenarios_organization_id'), table_name='forecast_scenarios')
    op.drop_index('ix_forecast_scenarios_org_kind', table_name='forecast_scenarios')
    op.drop_table('forecast_scenarios')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_index('ix_customers_org_name', table_name='customers')
    op.drop_index('ix_customers_org_erp', table_name='customers')
    op.drop_index('ix_customers_org_crm', table_name='customers')
    op.drop_index('ix_customers_org_billing', table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_commission_plans_organization_id'), table_name='commission_plans')
    op.drop_index('ix_commission_plans_org_effective', table_name='commission_plans')
    op.drop_table('commission_plans')
    op.drop_index(op.f('ix_ai_reporting_commentary_organization_id'), table_name='ai_reporting_commentary')
    op.drop_index('ix_ai_commentary_org_kind_period', table_name='ai_reporting_commentary')
    op.drop_table('ai_reporting_commentary')
    # ### end Alembic commands ###
