"""SaaS KPI calculation engine."""

from app.services.kpis.engine import (
    KpiInputs,
    KpiResults,
    calculate_arr,
    calculate_burn_multiple,
    calculate_cac,
    calculate_cac_payback_months,
    calculate_gross_mrr_churn_rate,
    calculate_grr,
    calculate_kpis,
    calculate_logo_churn_rate,
    calculate_ltv,
    calculate_ltv_to_cac,
    calculate_magic_number,
    calculate_net_mrr_churn_rate,
    calculate_nrr,
    calculate_operating_margin,
    calculate_pipeline_coverage,
    calculate_revenue_growth_rate,
    calculate_rule_of_40,
    calculate_sales_efficiency,
)

__all__ = [
    "KpiInputs",
    "KpiResults",
    "calculate_arr",
    "calculate_burn_multiple",
    "calculate_cac",
    "calculate_cac_payback_months",
    "calculate_gross_mrr_churn_rate",
    "calculate_grr",
    "calculate_kpis",
    "calculate_logo_churn_rate",
    "calculate_ltv",
    "calculate_ltv_to_cac",
    "calculate_magic_number",
    "calculate_net_mrr_churn_rate",
    "calculate_nrr",
    "calculate_operating_margin",
    "calculate_pipeline_coverage",
    "calculate_revenue_growth_rate",
    "calculate_rule_of_40",
    "calculate_sales_efficiency",
]
